"""Env settings."""
import os

POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB = os.getenv("POSTGRES_DB")

MATRYOSHKA_DIM = int(os.getenv("MATRYOSHKA_DIM", '512'))

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

NEETOCAL_API_KEY = os.getenv("NEETOCAL_API_KEY")
NEETOCAL_WORKSPACE = os.getenv("NEETOCAL_WORKSPACE")
NEETOCAL_MEETING_SLUG = os.getenv("NEETOCAL_MEETING_SLUG")
